build-device-type-json: show stderr on failure
balena-os/balena-yocto-scripts pull request #176
Opened 2020-10-21 20:12 UTC by jakogut

When building a device type JSON manifest, any syntax error is handled
by printing a message about node being unavailable, even when it's
installed and working.

Check that node is installed and executable before building the
manifest, and exit early with the existing message if not. Otherwise,
print stderr to the console for debugging.

2020-10-22 08:56 UTC, alexgg requested changes
@jakogut it's missing the footers (Change-type, Signed-off-by: etc) take a look at the commit guidelines and past commits to get an idea https://github.com/balena-io/process/blob/master/process/Commit_and_PR_Guidelines.md#commit-guidelines

2020-10-22 20:03 UTC, jakogut commented
@alexgg Thanks for the feedback, fixed.

2020-10-23 06:28 UTC, floion approved these changes

2020-10-23 08:05 UTC, alexgg approved these changes

2020-10-23 08:05 UTC, merged