Build and publish helper images with Flowzone
balena-os/balena-yocto-scripts pull request #324
Opened 2024-01-30 21:23 UTC by klutchell

Rather than build helper images on demand, we will publish them to ghcr.io with every revision of this project.

Change-type: minor

2024-01-31 23:10 UTC, klutchell commented
Integration tests: https://github.com/balena-os/balena-generic/pull/405

2024-02-02 14:17 UTC, alexgg requested changes
lgtm - I could approve as is. Just a note that some of the changes are on paths that are not currently used to it would maybe simplify things to PR the clean-up and then modify this PR.

But anyway I could approve it as it too as the paths are unused anyway - feel free to self certify.

2024-02-02 14:17 UTC, alexgg commented on automation/entry_scripts/balena-build-block.sh
@klutchell retesting all these changes is very time consuming - what I would suggest it to remove the paths that are not used (and probably never will), For example the whole `jenkins_build-blocks.sh` -> balena_build_block()  in `automation/include/balena-deploy.inc` and `balena-build-block.sh` is unused I believe.

I would PR that cleanup first, and then redo this PR to avoid having to re-implement those.

2024-02-02 18:52 UTC, alexgg approved these changes

2024-02-02 18:52 UTC, merged